services:
  - type: web
    name: swiftdl
    env: node
    plan: free
    buildCommand: npm install && pip install yt-dlp
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
